### ISSUE TITLE
Problems with GA4GH-rnaget-API-examples.ipynb

### ISSUE THREAD

**Issue by lauraclarke** [saupchurch/bioinformatics-tools#1]
I was trying to run this python notebook

I got to ds = loompy.connect(pcawg_loom_file)

and got this error. Not sure if there is a problem with my setup or the notebook itself

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    161         try:
--> 162             fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
    163         except IOError:

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    164             try:
--> 165                 fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
    166             except IOError:

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-11-a5ec48069b4c> in <module>
----> 1 ds = loompy.connect(pcawg_loom_file)

/anaconda3/lib/python3.7/site-packages/loompy/loompy.py in connect(filename, mode, validate, spec_version)
   1147                 Note: if validation is requested, an exception is raised if validation fails.
   1148 	"""
-> 1149         return LoomConnection(filename, mode, validate=validate, spec_version=spec_version)

/anaconda3/lib/python3.7/site-packages/loompy/loompy.py in __init__(self, filename, mode, validate, spec_version)
     82                 if validate:
     83                         lv = loompy.LoomValidator(version=spec_version)
---> 84                         if not lv.validate(filename):
     85                                 raise ValueError("\n".join(lv.errors) + f"\n{filename} does not appead to be a valid Loom file according to Loom spec version '{spec_version}'")
     86 

/anaconda3/lib/python3.7/site-packages/loompy/loom_validator.py in validate(self, path, strictness)
     46 		"""
     47                 valid1 = True
---> 48                 with h5py.File(path) as f:
     49                         valid1 = self.validate_spec(f)
     50                         if not valid1:

/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    310             with phil:
    311                 fapl = make_fapl(driver, libver, **kwds)
--> 312                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    313 
    314                 if swmr_support:

/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    165                 fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
    166             except IOError:
--> 167                 fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
    168     else:
    169         raise ValueError("Invalid mode; must be one of r, r+, w, w-, x, a")

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.create()

OSError: Unable to create file (unable to open file: name = 'full-loom-file.loom', errno = 17, error message = 'File exists', flags = 15, o_flags = a02)

**Comment by lauraclarke** [comment]
As a quick check, this also fails in standard python3 on the cmdline

(base) C02W829JHV2Q:ga4gh-rnaget-api laura$ python3
Python 3.7.1 (default, Dec 14 2018, 13:28:58)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> loompy.connect("full-loom-file.loom")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'loompy' is not defined
>>> import loompy
>>> loompy.connect("full-loom-file.loom")
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 162, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 165, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.7/site-packages/loompy/loompy.py", line 1149, in connect
    return LoomConnection(filename, mode, validate=validate, spec_version=spec_version)
  File "/anaconda3/lib/python3.7/site-packages/loompy/loompy.py", line 84, in __init__
    if not lv.validate(filename):
  File "/anaconda3/lib/python3.7/site-packages/loompy/loom_validator.py", line 48, in validate
    with h5py.File(path) as f:
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 167, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'full-loom-file.loom', errno = 17, error message = 'File exists', flags = 15, o_flags = a02)

**Comment by saupchurch** [comment]
I checked the notebook in my environment and it seems to be running OK.  I've dumped my virtualenv packages into a requirements.txt and added it to the repo.  Could you check your versions against those?  Another approach would be to turn off validation by adding `validate=False` to the `loopy.connect` call.

**Comment by hewgreen** [comment]
I installed your requirements in a virtual env and ran `jupyter notebook` from there but I still got the same error. I'm not sure how to check that the notebook is actually using the venv though.

**Comment by saupchurch** [comment]
Closing this as the notebook has been rewritten from the ground up.
